id: A8FF54738
title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
type: translation
pechas:
- I8CDD1878
- I24256BB5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:46.494184
  last_modified_at: 2023-01-04 13:09:46.494190
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8CDD1878/D6B5: 8F53
  I24256BB5/1879: 8F53
